# Site Settings
title: 박연오
email: bakyeono@gmail.com
description: "박연오의 개인 웹 페이지"
url: "http://bakyeono.net"
github_username: bakyeono 
license_url: "http://www.freeuse.or.kr/license/2.0/yg/index.htm"

# Where things are
source:       "."
destination:  "./_site"
plugins_dir:  "./_plugins"
layouts_dir:  "./_layouts"
data_dir:     "./_data"
includes_dir: "./_includes"
collections:  null

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      ["newpost", "publish", "start", "stop"]
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false

# Plugins
whitelist: []
gems:
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-feed

# Conversion
markdown:    kramdown
# highlighter: pygments
lsi:         false
excerpt_separator: "\n\n"

# Serving
detach:  false
port:    4000
host:    0.0.0.0
baseurl: "" # does not include hostname

# Backwards-compatibility
relative_permalinks: false

# Outputting
permalink:     "/post/:year-:month-:day-:title"
paginate:      100
paginate_path: "/page:num"
timezone:      "Asia/Seoul"
quiet:         true
defaults:      []

# Markdown Processors
kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     2..3
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

