#!/bin/bash

echo -n "Post Title(a-post-title): "
read POST_TITLE

echo -n "Post Tags(tag1 tag2 ...): "
read POST_TAGS

POST_DATE=`date +'%F'`
POST_TIME=`date +'%R'`

POST_FILE=_posts/$POST_DATE-$POST_TITLE.markdown

cat > $POST_FILE << _EOF_
---
layout: post
title: $POST_TITLE
author: 박연오(bakyeono@gmail.com)
date: $POST_DATE $POST_TIME
tags: $POST_TAGS
---
* table of contents
{:toc}


_EOF_

vi $POST_FILE

